//! Fail-closed object parsing (SPEC-2 §8; SPEC-1 §4.2 for the claims profile), issue #25.
//! Mirrors ../ts/src/strict.ts.
//!
//! The fail-closed rule was always normative for TAGS — an unrecognized `op`/`cmp`/`policy` MUST be
//! rejected, loudly, because that rejection is exactly what lets additive forms enter the closed
//! profiles without an `alg` bump. These helpers extend the identical discipline to the two
//! remaining ways a witness could silently ignore input it does not understand:
//!
//!   1. unknown KEYS      — {"op": "expand", …, "readng": "Post"} parsed as a legacy expand;
//!   2. ambiguous TAGS    — {"exact": "a", "prefix": "b"} silently taking the first arm.
//!
//! Both are "repair" in the SPEC-4 §2 sense, and repaired input is how two witnesses drift.
//!
//! `as_object` takes the known-key list BY SIGNATURE on purpose: the compiler — not vigilance — is
//! what guarantees every closed node in the grammar declares its keys. A node that is genuinely
//! open (an author-keyed map: `fix.bindings`, `schema.props`) says so by calling `as_open_map`, so
//! openness is always deliberate and visible rather than accidental.
//!
//! Error TEXT is not normative — only the rejection is — but it is worded to match the TypeScript
//! witness so the two can be cross-read.

use serde_json::{Map, Value};

/// Levenshtein distance, iterative two-row. Only ever runs on a rejection path.
fn edit_distance(a: &str, b: &str) -> usize {
    let a: Vec<char> = a.chars().collect();
    let b: Vec<char> = b.chars().collect();
    let mut prev: Vec<usize> = (0..=b.len()).collect();
    for i in 1..=a.len() {
        let mut cur = vec![i; b.len() + 1];
        for j in 1..=b.len() {
            let sub = prev[j - 1] + usize::from(a[i - 1] != b[j - 1]);
            cur[j] = (prev[j] + 1).min(cur[j - 1] + 1).min(sub);
        }
        prev = cur;
    }
    prev[b.len()]
}

/// The nearest known key, when it is near enough to be a plausible typo.
fn nearest<'a>(key: &str, known: &[&'a str]) -> Option<&'a str> {
    let mut best: Option<&str> = None;
    let mut best_dist = 3; // strictly less than 3 to suggest — beyond that it is a different word
    for k in known {
        let d = edit_distance(key, k);
        if d < best_dist {
            best_dist = d;
            best = Some(k);
        }
    }
    best
}

/// Per SPEC-2 §8's rejection-message SHOULD: an unrecognized name most often means version skew,
/// so say so instead of emitting a bare parse error.
fn unknown_key_message(key: &str, known: &[&str], what: &str) -> String {
    match nearest(key, known) {
        Some(suggestion) => format!("unknown key \"{key}\" on {what}; did you mean \"{suggestion}\"?"),
        None => format!(
            "unknown key \"{key}\" on {what} (expected one of: {}) — this may have been generated \
             by a newer rhizomatic; check whether support shipped in a release you haven't installed",
            known.join(", ")
        ),
    }
}

fn as_map<'a>(x: &'a Value, what: &str) -> Result<&'a Map<String, Value>, String> {
    x.as_object()
        .ok_or_else(|| format!("expected object for {what}"))
}

/// A CLOSED node: every key must be one this version of the grammar recognizes.
pub fn as_object<'a>(
    x: &'a Value,
    what: &str,
    known: &[&str],
) -> Result<&'a Map<String, Value>, String> {
    let o = as_map(x, what)?;
    for key in o.keys() {
        if !known.contains(&key.as_str()) {
            return Err(unknown_key_message(key, known, what));
        }
    }
    Ok(o)
}

/// An OPEN node: the keys are author-chosen data (hole names, property names), not grammar. Every
/// call site must be able to say why it is open — there are exactly two in the whole profile.
pub fn as_open_map<'a>(x: &'a Value, what: &str) -> Result<&'a Map<String, Value>, String> {
    as_map(x, what)
}

/// A DISPATCHED node: its key set depends on a discriminator (`op`). The tag is read and checked
/// first — the §8 tag rule — and the table row it names becomes the closed key set, so nothing is
/// read before it has been recognized. The table itself is the grammar, enforced.
pub fn as_dispatched<'a, 'k>(
    x: &'a Value,
    what: &str,
    tag_key: &str,
    table: &'k [(&'k str, &'k [&'k str])],
) -> Result<(&'a Map<String, Value>, &'k str), String> {
    let raw = as_map(x, what)?;
    let tag = raw.get(tag_key).and_then(Value::as_str);
    let row = tag.and_then(|t| table.iter().find(|(name, _)| *name == t));
    match row {
        Some(&(name, known)) => {
            let o = as_object(x, &format!("{what} {name}"), known)?;
            Ok((o, name))
        }
        None => Err(format!(
            "unknown {tag_key} {} on {what} — this term may have been generated by a newer \
             rhizomatic; check whether support for it shipped in a release you haven't installed",
            raw.get(tag_key).unwrap_or(&Value::Null)
        )),
    }
}

/// A TAGGED-UNION node: exactly one arm of a closed enumeration. Zero arms is malformed; several
/// is ambiguous, and picking one (the old first-match-wins behavior) is silent repair.
pub fn one_tag<'a, 'k>(
    x: &'a Value,
    tags: &'k [&'k str],
    what: &str,
) -> Result<(&'a Map<String, Value>, &'k str), String> {
    let o = as_object(x, what, tags)?;
    let present: Vec<&str> = tags
        .iter()
        .filter(|t| o.contains_key(**t))
        .copied()
        .collect();
    if present.is_empty() {
        return Err(format!("{what}: must be one of {}", tags.join(" | ")));
    }
    if present.len() > 1 {
        return Err(format!(
            "{what}: ambiguous — {} are both present, but exactly one is allowed",
            present
                .iter()
                .map(|p| format!("\"{p}\""))
                .collect::<Vec<_>>()
                .join(" and ")
        ));
    }
    Ok((o, present[0]))
}
