// Rebuild the shared schema/lens fixture ids and pins. Expected read outcomes are curated in
// the vector file and are deliberately not generated by the implementation under test.
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import {
  HYPER_SCHEMA_SCHEMA,
  claimsToJson,
  makeDelta,
  makeNegationClaims,
  parseSchema,
  parseTerm,
  publishHyperSchemaClaims,
  publishLensBindingClaims,
  publishSchemaClaims,
  schemaHash,
  termHash,
  type Claims,
} from "../src/index.js";

const path = resolve("../../vectors/l3-schema/governed-bindings.json");
const old = JSON.parse(await (await import("node:fs/promises")).readFile(path, "utf8")) as {
  hyperLoads: unknown[];
  schemaLoads: unknown[];
  lensLoads: unknown[];
};
const hyperA = { name: "DefinitionA", alg: 1, body: parseTerm("input") };
const hyperB = { name: "DefinitionB", alg: 1, body: HYPER_SCHEMA_SCHEMA.body };
const schemaA = parseSchema({
  name: "ReadingA",
  alg: 1,
  props: {},
  default: { pick: { order: "lexById" } },
});
const schemaB = parseSchema({
  name: "ReadingB",
  alg: 1,
  props: {},
  default: { pick: { order: { byTimestamp: "desc" } } },
});
const entries: Array<{ name: string; claims: Claims }> = [
  {
    name: "hyperA",
    claims: {
      ...publishHyperSchemaClaims(hyperA, "schema:governed", "A", 100),
      validFrom: 0,
      validUntil: 120,
    },
  },
  {
    name: "hyperB",
    claims: { ...publishHyperSchemaClaims(hyperB, "schema:governed", "B", 200), validFrom: 0 },
  },
  {
    name: "schemaA",
    claims: {
      ...publishSchemaClaims(schemaA, "schema:reading", "A", 100),
      validFrom: 0,
      validUntil: 120,
    },
  },
  {
    name: "schemaB",
    claims: { ...publishSchemaClaims(schemaB, "schema:reading", "B", 200), validFrom: 0 },
  },
  {
    name: "lensA",
    claims: {
      ...publishLensBindingClaims("lens:shared", hyperA, schemaA, "A", 100),
      validFrom: 50,
    },
  },
  {
    name: "lensB",
    claims: { ...publishLensBindingClaims("lens:shared", hyperB, schemaB, "B", 200), validFrom: 0 },
  },
  {
    name: "malformedLens",
    claims: {
      timestamp: 300,
      validFrom: 0,
      author: "A",
      pointers: [
        {
          role: "rhizomatic.lens.binds",
          target: { kind: "entity", entity: { id: "lens:malformed", context: "lens" } },
        },
        { role: "rhizomatic.lens.hyperschema", target: { kind: "primitive", value: "bad-pin" } },
        {
          role: "rhizomatic.lens.schema",
          target: { kind: "primitive", value: schemaHash(schemaA) },
        },
      ],
    },
  },
];
const id = (name: string) => makeDelta(entries.find((entry) => entry.name === name)!.claims).id;
entries.push(
  {
    name: "negateHyperA",
    claims: { ...makeNegationClaims("A", 70, id("hyperA")), validUntil: 90 },
  },
  {
    name: "negateSchemaA",
    claims: { ...makeNegationClaims("A", 70, id("schemaA")), validUntil: 90 },
  },
  {
    name: "negateLensA",
    claims: { ...makeNegationClaims("A", 70, id("lensA")), validUntil: 90 },
  },
  {
    name: "foreignNegateLensA",
    claims: { ...makeNegationClaims("B", 55, id("lensA")), validUntil: 65 },
  },
);
writeFileSync(
  path,
  JSON.stringify(
    {
      spec: "SPEC-3 §5.1-5.2",
      pins: {
        hyperA: termHash(hyperA.body),
        hyperB: termHash(hyperB.body),
        schemaA: schemaHash(schemaA),
        schemaB: schemaHash(schemaB),
      },
      deltas: entries.map((entry) => ({
        name: entry.name,
        id: makeDelta(entry.claims).id,
        claims: claimsToJson(entry.claims),
      })),
      hyperLoads: old.hyperLoads,
      schemaLoads: old.schemaLoads,
      lensLoads: old.lensLoads,
    },
    null,
    2,
  ) + "\n",
);
