// Fail-closed object parsing (SPEC-2 §8; SPEC-1 §4.2 for the claims profile), issue #25.
//
// The fail-closed rule was always normative for TAGS — an unrecognized `op`/`cmp`/`policy` MUST be
// rejected, loudly, because that rejection is exactly what lets additive forms enter the closed
// profiles without an `alg` bump. These helpers extend the identical discipline to the two
// remaining ways a witness could silently ignore input it does not understand:
//
//   1. unknown KEYS      — {"op": "expand", …, "readng": "Post"} parsed as a legacy expand;
//   2. ambiguous TAGS    — {"exact": "a", "prefix": "b"} silently taking the first arm.
//
// Both are "repair" in the SPEC-4 §2 sense, and repaired input is how two witnesses drift.
//
// `asObject` takes the known-key list BY SIGNATURE on purpose: the type checker — not vigilance —
// is what guarantees every closed node in the grammar declares its keys. A node that is genuinely
// open (an author-keyed map: `fix.bindings`, `schema.props`) says so by calling `asOpenMap`, so
// openness is always deliberate and visible rather than accidental.

// Levenshtein distance, iterative two-row. Only ever runs on a rejection path.
function editDistance(a: string, b: string): number {
  let prev = Array.from({ length: b.length + 1 }, (_, j) => j);
  for (let i = 1; i <= a.length; i++) {
    const cur = [i];
    for (let j = 1; j <= b.length; j++) {
      cur[j] = Math.min(
        prev[j]! + 1,
        cur[j - 1]! + 1,
        prev[j - 1]! + (a[i - 1] === b[j - 1] ? 0 : 1),
      );
    }
    prev = cur;
  }
  return prev[b.length]!;
}

// The nearest known key, when it is near enough to be a plausible typo.
function nearest(key: string, known: readonly string[]): string | undefined {
  let best: string | undefined;
  let bestDist = 3; // strictly less than 3 to suggest — beyond that it is a different word
  for (const k of known) {
    const d = editDistance(key, k);
    if (d < bestDist) {
      bestDist = d;
      best = k;
    }
  }
  return best;
}

// Per SPEC-2 §8's rejection-message SHOULD: an unrecognized name most often means version skew,
// so say so instead of emitting a bare parse error.
function unknownKeyMessage(key: string, known: readonly string[], what: string): string {
  const suggestion = nearest(key, known);
  if (suggestion !== undefined) {
    return `unknown key "${key}" on ${what}; did you mean "${suggestion}"?`;
  }
  return (
    `unknown key "${key}" on ${what} (expected one of: ${known.join(", ")}) — ` +
    `this may have been generated by a newer rhizomatic; check whether support shipped in a ` +
    `release you haven't installed`
  );
}

function asRecord(x: unknown, what: string): Record<string, unknown> {
  if (typeof x !== "object" || x === null || Array.isArray(x)) {
    throw new Error(`expected object for ${what}`);
  }
  return x as Record<string, unknown>;
}

// A CLOSED node: every key must be one this version of the grammar recognizes.
export function asObject(
  x: unknown,
  what: string,
  known: readonly string[],
): Record<string, unknown> {
  const o = asRecord(x, what);
  for (const key of Object.keys(o)) {
    if (!known.includes(key)) throw new Error(unknownKeyMessage(key, known, what));
  }
  return o;
}

// An OPEN node: the keys are author-chosen data (hole names, property names), not grammar. Every
// call site must be able to say why it is open — there are exactly two in the whole profile.
export function asOpenMap(x: unknown, what: string): Record<string, unknown> {
  return asRecord(x, what);
}

// A DISPATCHED node: its key set depends on a discriminator (`op`). The tag is read and checked
// first — the §8 tag rule — and the table row it names becomes the closed key set, so nothing is
// read before it has been recognized. The table itself is the grammar, enforced.
export function asDispatched(
  x: unknown,
  what: string,
  tagKey: string,
  table: Readonly<Record<string, readonly string[]>>,
): { o: Record<string, unknown>; tag: string } {
  const raw = asRecord(x, what);
  const tag = raw[tagKey];
  if (typeof tag !== "string" || !Object.prototype.hasOwnProperty.call(table, tag)) {
    throw new Error(
      `unknown ${tagKey} ${String(tag)} on ${what} — this term may have been generated by a ` +
        `newer rhizomatic; check whether support for it shipped in a release you haven't installed`,
    );
  }
  return { o: asObject(raw, `${what} ${tag}`, table[tag]!), tag };
}

// A TAGGED-UNION node: exactly one arm of a closed enumeration. Zero arms is malformed; several
// is ambiguous, and picking one (the old first-match-wins behavior) is silent repair.
export function oneTag(
  x: unknown,
  tags: readonly string[],
  what: string,
): { o: Record<string, unknown>; tag: string } {
  const o = asObject(x, what, tags);
  const present = tags.filter((t) => o[t] !== undefined);
  if (present.length === 0) {
    throw new Error(`${what}: must be one of ${tags.join(" | ")}`);
  }
  if (present.length > 1) {
    throw new Error(
      `${what}: ambiguous — ${present.map((p) => `"${p}"`).join(" and ")} are both present, ` +
        `but exactly one is allowed`,
    );
  }
  return { o, tag: present[0]! };
}
